/**
 * Pure JQL builder for "One-Click Sprint Start" (one-click-sprint-start.md). Generates the 4
 * track filters (Roadmap/Tech Debt/Internal Bug/External Bug) for a team from its claimed
 * sub-components, its per-track Issue Type config, and a Sprint's Fix Version(s) — replacing
 * hand-typed JQL.
 *
 * Follows the `IN (...)`-composition idiom already established in `bug-report/matrix.mjs`,
 * deliberately WITHOUT that module's "resolve a saved filter's live JQL" complexity: every track
 * here is fresh generated text, never a filter-id reference. No Prisma, no fetch — plain-Node
 * testable (the seeding.mjs/metrics.mjs precedent). Field naming/order/quoting/`ORDER BY` are
 * pinned to a real generated JQL sample from Naveen's Jira instance (2026-07-27 correction).
 */
import {
  resolveIssueTypes,
  DEFAULT_EXTERNAL_BUG_PROJECT_KEY,
  SUB_COMPONENT_FIELD,
} from "../jira/issue-type-defaults.mjs";

/** Track → user-facing filter name. */
export const TRACK_NAMES = {
  FEATURE: "Roadmap",
  TECH_DEBT: "Tech Debt",
  INTERNAL_BUG: "Internal Bugs",
  SUPPORT: "External Bugs",
};

/** Tracks generated by one-click sprint start, in WORKFLOWS priority order. */
export const SPRINT_START_TRACKS = ["FEATURE", "TECH_DEBT", "SUPPORT", "INTERNAL_BUG"];

/**
 * Group a team's claimed `JiraSubComponent` rows (each with its `component` relation loaded) into
 * `componentGroups` for {@link buildAllTrackJql} — one entry per parent JiraComponent.
 * @param {Array<{ name: string, component: { projectKey: string, name: string } }>} subComponents
 * @returns {Array<{ projectKey: string, componentName: string, subComponentNames: string[] }>}
 */
export function groupSubComponentsByComponent(subComponents) {
  const groups = new Map();
  for (const sub of subComponents) {
    const key = `${sub.component.projectKey}:${sub.component.name}`;
    if (!groups.has(key)) {
      groups.set(key, {
        projectKey: sub.component.projectKey,
        componentName: sub.component.name,
        subComponentNames: [],
      });
    }
    groups.get(key).subComponentNames.push(sub.name);
  }
  return [...groups.values()];
}

// Jira only requires quoting a literal when it contains whitespace (e.g. "Tech Story",
// "Tap Ticket") — bare identifiers like project keys, sub-component names, and Fix Version
// strings are left unquoted, matching a real generated JQL sample from Naveen's Jira instance.
function quoteIfNeeded(value) {
  const str = String(value);
  return /\s/.test(str) ? `"${str.replace(/["\\]/g, "\\$&")}"` : str;
}

function compareClause(field, values) {
  return values.length === 1
    ? `${field} = ${quoteIfNeeded(values[0])}`
    : `${field} IN (${values.map(quoteIfNeeded).join(", ")})`;
}

// `field IS EMPTY` — an absence clause. `quoteIfNeeded`/`compareClause` only build `=`/`IN`, so the
// Needs-attention track (which selects on a field being UNSET) needs this separately.
function emptyClause(field) {
  return `${field} IS EMPTY`;
}

// Emails carry no whitespace, so `quoteIfNeeded` would leave them BARE — which breaks Jira's
// `assignee IN (...)` clause (assignee literals must be quoted strings). Roster emails are validated
// to contain no double-quote or whitespace (memberEmail zod), so this can never inject.
function quoteEmail(value) {
  return `"${String(value)}"`;
}

/**
 * One track's JQL: `type ... AND project ... [AND <field> ... for each componentClause] AND
 * [fixversion ...] ORDER BY issuetype ASC` — field order, `type`/`fixversion` naming, unquoted
 * bare literals, and the trailing ORDER BY all match a real generated JQL sample from Naveen's
 * Jira instance. `componentClauses` is an ordered list so a track can AND together more than one
 * component-ish field (e.g. External Bug ANDs the parent Component with the sub-component field).
 * @param {{ projectKeys: string[], issueTypes: string[], componentClauses?: Array<{ field: string, values: string[] }>, fixVersions?: string[] }} args
 * @returns {string}
 */
export function buildTrackJql({ projectKeys, issueTypes, componentClauses = [], fixVersions = [] }) {
  const clauses = [compareClause("type", issueTypes), compareClause("project", projectKeys)];
  for (const { field, values } of componentClauses) {
    if (values.length > 0) clauses.push(compareClause(field, values));
  }
  if (fixVersions.length > 0) clauses.push(compareClause("fixversion", fixVersions));
  return `${clauses.join(" AND ")} ORDER BY issuetype ASC`;
}

/**
 * All 4 tracks' JQL for a team. Roadmap/Tech Debt/Internal Bug scope by the team's own
 * project(s) + fine-grained claimed sub-component names; External Bug scopes by the fixed `ENG`
 * project + the PARENT Component name(s) only (decision 7, one-click-sprint-start.md — ENG issues
 * may carry no sub-component tag at all, so this track can't be sliced as finely as the others).
 *
 * @param {object} team the Team row (for `resolveIssueTypes` overrides)
 * @param {Array<{ projectKey: string, componentName: string, subComponentNames: string[] }>} componentGroups
 *   one entry per parent JiraComponent the team has sub-components claimed under (normally one)
 * @param {string[]} fixVersions the Sprint's fixVersions
 * @returns {{ FEATURE: string, TECH_DEBT: string, INTERNAL_BUG: string, SUPPORT: string }}
 */
export function buildAllTrackJql({ team, componentGroups, fixVersions = [] }) {
  const ownProjectKeys = [...new Set(componentGroups.map((g) => g.projectKey))];
  const ownSubComponentNames = componentGroups.flatMap((g) => g.subComponentNames);
  const parentComponentNames = [...new Set(componentGroups.map((g) => g.componentName))];

  const ownTrack = (workflowType) =>
    buildTrackJql({
      projectKeys: ownProjectKeys,
      issueTypes: resolveIssueTypes(team, workflowType),
      componentClauses: [{ field: SUB_COMPONENT_FIELD, values: ownSubComponentNames }],
      fixVersions,
    });

  return {
    FEATURE: ownTrack("FEATURE"),
    TECH_DEBT: ownTrack("TECH_DEBT"),
    INTERNAL_BUG: ownTrack("INTERNAL_BUG"),
    // External Bug ANDs the parent Component (how ENG issues are coarsely tagged, decision 7)
    // together with the team's own fine-grained sub-component names (per Naveen, 2026-07-27).
    SUPPORT: buildTrackJql({
      projectKeys: [DEFAULT_EXTERNAL_BUG_PROJECT_KEY],
      issueTypes: resolveIssueTypes(team, "SUPPORT"),
      componentClauses: [
        { field: "component", values: parentComponentNames },
        { field: SUB_COMPONENT_FIELD, values: ownSubComponentNames },
      ],
      fixVersions,
    }),
  };
}

/** Display name for the always-on Needs-attention hygiene track (not a sprint-start track). */
export const NEEDS_ATTENTION_NAME = "Needs attention";

/**
 * JQL for the always-on "Needs attention" hygiene track (needs-attention-roster.md). Every other
 * track scopes by the `"sub-component[dropdown]"` field, so an item missing that tag is invisible on
 * the board — its only reliable team identity is the ASSIGNEE. This surfaces the team's own work (by
 * roster email) that lacks a sub-component OR a fix version and isn't already Done:
 *
 *   assignee IN ("a@x.com", "b@x.com") AND project in (GM)
 *     AND ("sub-component[dropdown]" IS EMPTY OR fixVersion IS EMPTY)
 *     AND statusCategory != Done ORDER BY updated DESC
 *
 * Returns `null` when there is nothing to scope by (empty roster or no project keys) — callers must
 * never emit an unbounded `assignee IN ()` or a project-less scan across everything the token sees.
 *
 * @param {{ memberEmails?: string[], projectKeys?: string[], excludeDone?: boolean }} args
 * @returns {string|null}
 */
export function buildNeedsAttentionJql({ memberEmails, projectKeys, excludeDone = true }) {
  const emails = [
    ...new Set((memberEmails ?? []).map((e) => String(e).trim().toLowerCase()).filter(Boolean)),
  ];
  const projects = [...new Set((projectKeys ?? []).map((p) => String(p).trim()).filter(Boolean))];
  if (emails.length === 0 || projects.length === 0) return null;

  const clauses = [
    `assignee IN (${emails.map(quoteEmail).join(", ")})`,
    compareClause("project", projects),
    `(${emptyClause(SUB_COMPONENT_FIELD)} OR ${emptyClause("fixVersion")})`,
  ];
  if (excludeDone) clauses.push("statusCategory != Done");
  return `${clauses.join(" AND ")} ORDER BY updated DESC`;
}
